#!/bin/sh
#RR_DATA should refer to the directory in which ReveladeRevolution data files are placed.
#RR_DATA=~/reveladerevolution
RR_DATA=.

# RR_BIN should refer to the directory in which ReveladeRevolution executable files are placed.
RR_BIN=${RR_DATA}/bin_unix

# RR_OPTIONS contains any command line options you would like to start ReveladeRevolution with.
#RR_OPTIONS="-f"
RR_OPTIONS="-q${HOME}/.reveladerevolution"

# SYSTEM_NAME should be set to the name of your operating system.
#SYSTEM_NAME=Linux
SYSTEM_NAME=`uname -s`

# MACHINE_NAME should be set to the name of your processor.
#MACHINE_NAME=i686
MACHINE_NAME=`uname -m`


if [ -x ${RR_BIN}/tess_client ]
then
  cd ${RR_DATA}
  exec ${RR_BIN}/tess_client ${RR_OPTIONS} "$@"
else
  echo "Your platform does not have a pre-compiled ReveladeRevolution client."
  echo "Please follow the following steps to build a native client:"
  echo "1) Ensure you have the SDL, SDL-image, SDL-mixer, and OpenGL libraries installed."
  echo "2) Change directory to src/ and type \"make install\"."
  echo "3) If the build succeeds, return to this directory and run this script again."
  exit 1
fi

