// This file is automatically generated by cmake.
// Do not include in a precompiled header, rather include only where you have to.

#define RR_VERSION_TYPE_RELEASE     0
#define RR_VERSION_TYPE_DEVELOPMENT 1

#define RR_VERSION_TYPE             ${RR_VERSION_TYPE}

#define RR_VERSION_MAJOR            ${RR_VERSION_MAJOR}
#define RR_VERSION_MINOR            ${RR_VERSION_MINOR}
#define RR_VERSION_PATCH            ${RR_VERSION_PATCH}
#define RR_VERSION_TAG              ${RR_VERSION_TAG}

#define RR_VERSION_VAL              ((RR_VERSION_MAJOR << 16) | (RR_VERSION_MINOR <<  8) | (RR_VERSION_PATCH))

#define RR_VERSION_STRING   "${RR_VERSION}"
#define RR_VERSION_DATE     "${DATE}"
